name: Build and Push the Docker Image

on: [workflow_dispatch]

env: 
    IMAGE_NAME: ${{secrets.DOCKERHUB_USERNAME}}/${{ github.event.repository.name }}

jobs:
    build-push-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout APP
              uses: actions/checkout@v4
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}
            
            - name: Extract MetaData
              id: metadata
              uses: docker/metadata-action@v4
              with:
                images: |
                    ${{env.IMAGE_NAME}}
                tags: |
                    type=semver,pattern={{version}}
                    type=semver,pattern={{major}}.{{minor}}

            - name: Build Image and Push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ steps.metadata.outputs.tags }}
                labels: ${{ steps.metadata.outputs.labels }} 
