name: CI
on:
    pull_request:
        branches: [main]

concurrency:
    group: ${{github.workflow}}-${{github.event.pull_request.number}}
    cancel-in-progress: true

jobs:
    run-tests:
        uses: ./.github/workflows/test-udemy.yaml
        secrets: inherit # is to pass all the secrets from test-udemy.yaml file. Practic sa mosteneasca secretele
