name: Run Tests

on:
    workflow_run:
        workflows: [Build and Push the Docker Image]
        types:
            - completed
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: node:20-alpine
        services:
            app:
                image: cla0207/nextjs-started:latest
                ports:
                    - 3000:3000
                env:
                    MONGODB_URI: "mongodb://admin:password@localhost:27017/mydatabase?authSource=admin" 
            mongodb:
                image: mongo:6.0
                ports:
                    - 27017:27017
                env:
                    MONGO_INITDB_ROOT_USERNAME: admin
                    MONGO_INITDB_ROOT_PASSWORD: password
        steps:
            - name: Checkout APP
              uses: actions/checkout@v4

            - name: Install system dependencies
              run: |
                apk update
                apk add --no-cache curl

            - name: Install dependencies
              run: npm install

            - name: Check the url
              run: curl -v http://localhost:3000/

            - name: Run the tests
              run: npm run test

